### ISSUE TITLE
Unable to get file icons in GitLab and BitBucket 

### ISSUE THREAD

**Issue by sanjeevkpandit** [dderevjanik/github-vscode-icons#2]
The icons in the files list under any merge-request in Gitlab or BitBucket is showing a buffering icon instead of file icon.

Below is a screnshot of README in gitlab:
![icon-issue](https://user-images.githubusercontent.com/13619272/39515301-6a49f910-4e19-11e8-91ec-349cf8ba6d47.png)

The buffering icon showing in the image above is _[chrome-extension://hoccpcefjcgnabbmojbfoflggkecmpgd/images/animation.gif](chrome-extension://hoccpcefjcgnabbmojbfoflggkecmpgd/images/animation.gif)_

Same happens for the files in the merge-requests on both Gitlab and BitBucket.

Disabling the extension shows the file icon.

Steps to replicate:

* Install extension on Chrome/Chromium
* View any gitlab repo or merge-requests
* View any bitbucket merge-requests

**Comment by dderevjanik** [comment]
Hi,

Thank you very much for filling an issue. I will try to fix ASAP.

**Comment by dderevjanik** [comment]
I fixed an issue with loading icon in Gitlab, but I wasn't able to fix Bitbucket icons, because they changed all classnames to obsfuscated ones.

![bb](https://user-images.githubusercontent.com/4524497/39550839-022f2bc6-4e63-11e8-9dbd-6907c88aea39.png)

Changes were published to chrome store (version 1.11)

**Comment by sanjeevkpandit** [comment]
Hi @dderevjanik,

It looks all good now. Thanks a lot.
